import { Button, Card, CardContent, Typography, Container } from '@mui/material';
import { Box } from '@mui/system';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import PR00F_OF_L1F3 from '../components/PR00F_0F_L1F3';
import S33DB4NK from '../components/S33DB4NK/S33DB4NK';
import F4RM3R from '../components/F4RM3R';

const Home: NextPage = () => {
  return (
    <Box 
      sx={{ 
        display: 'flex', 
        flexDirection: 'column', 
        alignItems: 'center', 
        justifyContent: 'center',
        minHeight: '100vh',
      }}
    >
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Container component="main" maxWidth="sm">
        <p></p>
        <ConnectButton />

        <Box sx={{ my: 4 }}>
          <Card sx={{ boxShadow: 1 }}>
            <CardContent>
              <Typography 
                variant="h5" 
                component="div"
                textAlign='center'
              >
                PR00F 0F L1F3
              </Typography>
              <Typography color="text.secondary">
                Join the BR33D3RS in a web3 Revolution. Bringing proof of growth to the optimism SuperChain
              </Typography>
              <PR00F_OF_L1F3 />
            </CardContent>
          </Card>
        </Box>
        <Box sx={{ my: 4 }}>
          <Card sx={{ boxShadow: 1 }}>
            <CardContent>
              <Typography 
                variant="h5" 
                component="div"
              >
                S33DB4NK®
              </Typography>
              <S33DB4NK />
              <Typography color="text.secondary">
                Join the BR33D3RS in a web3 Revolution. Bringing proof of growth to the optimism SuperChain
              </Typography>
            </CardContent>
          </Card>
        </Box>
        <Box sx={{ my: 4 }}>
          <Card sx={{ boxShadow: 1 }}>
            <CardContent>
              <Typography 
                variant="h5" 
                component="div"
              >
                S33D D3T41LS
              </Typography>
              <Typography color="text.secondary">
                Join the BR33D3RS in a web3 Revolution. Bringing proof of growth to the optimism SuperChain
              </Typography>
            </CardContent>
          </Card>
        </Box>
        <Box sx={{ my: 4 }}>
          <Card sx={{ boxShadow: 1 }}>
            <CardContent>
              <Typography 
                variant="h5" 
                component="div"
              >
                F4RM3RS 4LM4N4C
              </Typography>
              <F4RM3R />
              <Typography color="text.secondary">
                Join the BR33D3RS in a web3 Revolution. Bringing proof of growth to the optimism SuperChain
              </Typography>
            </CardContent>
          </Card>
        </Box>
        

      </Container>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          BR33D3R® || S01L® || S33DB4NK® protocols are property of the people  C/O FOAMLabs® 
        </a>
      </footer>
    </Box>
  );
};

export default Home;